[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello-world = "Hj9Hb5XYVqZNcPwVswyT47rtpozHW6NdjoP3FubmYFDr"
solana_contracts_workspace = "Fgwuu9texvCmbq7WT7DcujyyW8HsRytfVnSEUmeeQKoM"

[programs.devnet]
hello-world = "Hj9Hb5XYVqZNcPwVswyT47rtpozHW6NdjoP3FubmYFDr"
solana_contracts_workspace = "Fgwuu9texvCmbq7WT7DcujyyW8HsRytfVnSEUmeeQKoM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
